version: "2.2"
services:
  db:
    image: jsurf/rpi-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "****"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "****"
      MYSQL_PASSWORD: "****"
    networks:
      - internal
    ports:
      - 3306:3306
    volumes:
      - /opt/nextcloud/db:/var/lib/mysql
  nextcloud:
    image: nextcloud:17.0.1-apache
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - /opt/nextcloud/data:/var/www/html
      - /mnt/****:/var/www/html/data
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.yourwebsite.com`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.yourwebsite.com`)"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=http"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=16000000000"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=16000000000"
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=1000000000"
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=1000000000"
      - "traefik.http.middlewares.headersettings.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.headersettings.headers.framedeny=true"
      - "traefik.http.middlewares.headersettings.headers.sslredirect=true"
      - "traefik.http.middlewares.headersettings.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.headersettings.headers.stsPreload=true"
      - "traefik.http.middlewares.headersettings.headers.stsSeconds=15552000"
      - "traefik.http.routers.nextcloud-secure.middlewares=limit,headersettings"

networks:
  web:
    external: true
  internal:
    external: false
